### ISSUE TITLE
Change default compiler from gcc to clang mac os x

### ISSUE THREAD

**Issue by lfiaschi** [ukoethe/vigra#132]
while compiling vigra cmake sets gcc as default compiler. Mac os x gcc sticks with version 4.2 which is unable to support C++11. For this reason, vigra should be required to compile with clang.

P.s.
At the moment, clang has only partial support for c++11: it does not support advanced features such as: stl threads, range initialisation etc ...

**Comment by ukoethe** [comment]
Issue is now obsolete.
