### ISSUE TITLE
MultiArrayShapeConverter not available for type `int` on 64bit machines

### ISSUE THREAD

**Issue by burgerdev** [ukoethe/vigra#175]
I wanted to provide a boost-python interface for my vigranumpy extension, but it kept complaining that ```vigra::TinyVector<int, 3>``` was not convertible to tuple and vice-versa. 

The reason for this is that `MultiArrayShapeConverter`s are just registered for 

```c
MultiArrayIndex, float, double, short, npy_intp
```

and on (my) 64-bit machines `MultiArrayIndex`  and `npy_intp` are both `long`. Is this intentional and I am missing something? 

I managed to 'fix' this like that:
```diff
diff --git a/vigranumpy/src/core/converters.cxx b/vigranumpy/src/core/converters.cxx
index 3677188..225da9e 100644
--- a/vigranumpy/src/core/converters.cxx
+++ b/vigranumpy/src/core/converters.cxx
@@ -326,6 +326,9 @@ void registerNumpyShapeConvertersAllTypes()
     registerNumpyShapeConvertersOneType<short>();
     if(typeid(npy_intp) != typeid(MultiArrayIndex))
         MultiArrayShapeConverter<0, npy_intp>();
+
+    if(typeid(int) != typeid(MultiArrayIndex))
+        registerNumpyShapeConvertersOneType<int>();
 }
 
 #if 0 // FIXME: reimplement to replace the Python versions for consistence?
```

**Comment by ukoethe** [comment]
Fixed in ee769fa9e922afea9ce26b672f94040213b230d3
