### ISSUE TITLE
'Make check' fails due to missing dependencies

### ISSUE THREAD

**Issue by minhb** [ukoethe/vigra#183]
Hello,

I ran the command 'make check' to run all the test suites. I came across this error:

***********************Make check output*********************************************************

Scanning dependencies of target test_multiarray_chunked
[ 65%] Building CXX object test/multiarray/CMakeFiles/test_multiarray_chunked.dir/test_chunked.cxx.o
In file included from /home/minh/Dropbox/GSoC/06.Project/vigra/include/vigra/multi_array_chunked.hxx:139:0,
                 from /home/minh/Dropbox/GSoC/06.Project/vigra/test/multiarray/test_chunked.cxx:40:
/home/minh/Dropbox/GSoC/06.Project/vigra/include/vigra/hdf5impex.hxx:49:18: fatal error: hdf5.h: No such file or directory
 #include <hdf5.h>
                  ^
compilation terminated.
make[3]: *** [test/multiarray/CMakeFiles/test_multiarray_chunked.dir/test_chunked.cxx.o] Error 1
make[2]: *** [test/multiarray/CMakeFiles/test_multiarray_chunked.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2

***********************END- Make check output******************************************************

I don't have HDF5 installed on my computer. Here is the output of cmake:

***********************cmake output*********************************************************************
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring VIGRA version 1.10.0
-- Checking template recursion depth: ok
-- Searching for ZLIB
--    in default locations
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Searching for TIFF
--    in default locations
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.3") 
-- Searching for JPEG
--    in default locations
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Searching for PNG
--    in default locations
-- Could NOT find PNG (missing:  PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Searching for FFTW3
--    in default locations
-- Could NOT find FFTW3 (missing:  FFTW3_LIBRARY FFTW3_INCLUDE_DIR) 
-- Searching for FFTW3F
--    in default locations
-- Could NOT find FFTW3F (missing:  FFTW3F_LIBRARY FFTW3F_INCLUDE_DIR) 
-- Searching for HDF5
--    in default locations
-- Could NOT find HDF5 (missing:  HDF5_CORE_LIBRARY HDF5_HL_LIBRARY HDF5_ZLIB_OK HDF5_SZLIB_OK HDF5_INCLUDE_DIR HDF5_SUFFICIENT_VERSION) 
-- Searching for Boost (at least version 1.40.0)
--    in default locations
-- Could NOT find Boost
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.6", minimum required is "2") 
-- Checking VIGRANUMPY_DEPENDENCIES
-- Found Python libraries: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- Found Python includes:  /usr/include/python2.7
-- Searching for Boost (at least version 1.40.0)
--    in default locations
-- Could NOT find Boost
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy.distutils.misc_util
-- Could NOT find Python numpy ('import numpy.distutils.misc_util' failed)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named nose
-- Could NOT find Python nosetests ('import nose' failed)
-- Could NOT find sphinx documentation generator
-- Could NOT find VIGRANUMPY_DEPENDENCIES (missing:  Boost_PYTHON_FOUND PYTHON_NUMPY_INCLUDE_DIR) 
-- ** WARNING: test_classifier::RFHDF5Test() will not be executed
-- ** WARNING: test_fourier will not be executed
-- ** WARNING: test_hdf5impex will not be executed
-- ** WARNING: test_features will not be executed
-- ---------------------------------------------------------
-- VIGRA configuration information:
-- ---------------------------------------------------------
--   Using ZLIB  libraries: /usr/lib/x86_64-linux-gnu/libz.so
--   PNG libraries not found (PNG support disabled)
--   Using TIFF libraries: /usr/lib/x86_64-linux-gnu/libtiff.so
--   Using JPEG libraries: /usr/lib/x86_64-linux-gnu/libjpeg.so
--   OpenEXR disabled by user (WITH_OPENEXR=0)
--   FFTW libraries not found (FFTW support disabled)
--   HDF5 libraries not found (HDF5 support disabled)
--   Boost Graph Library disabled by user (WITH_BOOST_GRAPH=0)
--   LEMON graph library disabled by user (WITH_LEMON=0)
--   Vigranumpy dependencies not found (vigranumpy disabled)
-- ---------------------------------------------------------
--   building shared lib
--   binaries will be generated in: /home/minh/Dropbox/GSoC/06.Project/build
--   manuals will be generated in: /home/minh/Dropbox/GSoC/06.Project/vigra/doc
-- ---------------------------------------------------------
--   includes will be installed at: /home/minh/Dropbox/GSoC/06.Project/install/include
--   libraries will be installed at: /home/minh/Dropbox/GSoC/06.Project/install/lib
--   binaries will be installed at: /home/minh/Dropbox/GSoC/06.Project/install/bin
--   vigra manuals will be installed at: /home/minh/Dropbox/GSoC/06.Project/install/doc/vigra/index.html
--   vigranumpy will NOT be installed
-- 
-- Consider setting DEPENDENCY_SEARCH_PREFIX to find missing libraries
-- ---------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /home/minh/Dropbox/GSoC/06.Project/build

***********************END - cmake output*************************************************************

As Ulli said: 'make check'  should skip test in which the library is not found. If you can not produce the this case, please let me know.

Cheers, 
Minh

**Comment by ukoethe** [comment]
Fixed in https://github.com/ukoethe/vigra/commit/6338d1def4477b372b46d38ab63acc798889a9cb
