### ISSUE TITLE
Filters should allow sigma=0.0 for some axes

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#200]
If one wants to filter an ND image, but not across all axes, that should be possible by passing a sigma of 0.0 for the unfiltered axes.  For example, `scipy.ndimage.guassian_filter` permits the following:

    >>> from scipy.ndimage import gaussian_filter
    >>> a = numpy.ones((100,100,100,1), dtype=numpy.float32)
    >>> gaussian_filter(a, [1.1, 0.0, 1.1, 0.0])

... but a similar call to vigra results in an precondition violation:

    >>> import vigra
    >>> a = numpy.ones((100,100,100,1), dtype=numpy.float32)
    >>> a = vigra.taggedView(a, 'zyxc')
    >>> vigra.filters.gaussianSmoothing(a, [1.1, 0.0, 1.1])

    RuntimeError: 
    Precondition violation!
    gaussianSmoothMultiArray(): Scale would be imaginary or zero.
    (/magnetic/mac-binary-bpd/src/vigra-git/include/vigra/multi_convolution.hxx:146)

The solution to this issue might involve some strange corner cases that require some extra care.  For example: normally `vigra.filters.structureTensorEigenvalues()` returns 3-channel output data for 3D input data.  But if `sigma=[1,0,1]`, should the output have only 2 channels?

**Comment by ukoethe** [comment]
Gaussian derivatives with scale 0 are undefined. Gaussian smoothing with scale 0 is equivalent to identity filtering and is supported as of b45ff00f4efa7ab71e34a7e45f420687ec6e48fd.
