### ISSUE TITLE
axistags not preserved in vigra.sampling.ImagePyramid

### ISSUE THREAD

**Issue by svenpeter42** [ukoethe/vigra#228]
# Summary:
When using the vigranumpy bindings, vigra.sampling.ImagePyramid and a ScalarImage (i.e. an image without a channel axis) the y axis is silently converted to a meaningless channels axis when using createLevels.
This in turn makes the generation of the next pyramid level fail since the channel axis is not downsampled.

# Steps to reproduce:

```
cat << EOF | python
import vigra
img = vigra.ScalarImage((8,8))
p = vigra.sampling.ImagePyramid(img)
p.createLevel(2)
for i_lvl, lvl in enumerate(p):
    print i_lvl, lvl.shape, "Last axis: ", lvl.axistags[1]
EOF
```

# Expected Result
```
0 (8, 8) Last axis:  AxisInfo: 'y' (type: Space)
1 (4, 4) Last axis:  AxisInfo: 'y' (type: Space)
2 (2, 2) Last axis:  AxisInfo: 'y' (type: Space)
```

# Actual result
```
0 (8, 8) Last axis:  AxisInfo: 'y' (type: Space)
1 (4, 4) Last axis:  AxisInfo: 'c' (type: Channels)
2 (2, 4) Last axis:  AxisInfo: 'c' (type: Channels)
```

**Comment by ukoethe** [comment]
fixed by 971e3dc84def11138ba7875f1884ca61b9ff054a
