### ISSUE TITLE
Memory leak in `vigra.analysis.extractRegionFeatures()`

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#230]
As @DerThorsten discovered recently, there seems to be a strange memory leak in `vigra.analysis.extractRegionFeatures()`.  The leak can be observed using the following python code from @DerThorsten.  It has not yet been determined if the leak can be reproduced in pure C++ (no one has tried yet).

```
import vigra
import psutil
img  = vigra.impex.readImage("Lenna.png")[0:100,0:100]
sp,nseg = vigra.analysis.slicSuperpixels(img,10, 10)

i=0
while(1):
    i+=1
    if(i%10 == 0):
        print psutil.phymem_usage()
    res = vigra.analysis.extractRegionFeatures(image=img, labels=sp)
```
The RAM usage printed above will increase for every iteration and won't ever decrease...

![lenna](https://cloud.githubusercontent.com/assets/1655821/6448993/a83dd5a2-c0eb-11e4-8e08-d087f2b34165.png)

**Comment by burgerdev** [comment]
I tried to reproduce this in C++ using adapted vigra unit tests, but got no unexpected behaviour. Possibly the bug is somewhere in the glue.

**Comment by DerThorsten** [comment]
i would search in pythonaccumulator.hxx
A lot of:
 VIGRA_UNIQUE_PTR<Accumulator> res(new Accumulator(permutation)) 
is going on there.

**Comment by ukoethe** [comment]
A first look into this revealed an interesting fact: If one just calls
```
res = vigra.analysis.extractRegionFeatures(image=img, labels=sp)
```
(without a loop) the reference counter of `res` has value `7` instead of the expected `1` for a newly created object. No wonder that nothing is ever destructed.

**Comment by stuarteberg** [comment]
Wow, one little missing line... Nice fix!

**Comment by stuarteberg** [comment]
Ideally, this mistake would have been caught by the compiler's `-Wdelete-non-virtual-dtor` setting (which is also activated via `-Wall`.  I wonder why it didn't.
