### ISSUE TITLE
AxisTags API improvement: list-like vs. dict-like

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#231]
One occasional cause of bugs in ilastik is confusion over whether or not `vigra.AxisTags` is "list-like" or "dict-like".

Sometimes it looks like a dict, whose keys are the axis names:
```
In [1]: import vigra

In [2]: tags = vigra.defaultAxistags('xyz')

In [3]: tags['x']
Out[3]: AxisInfo: 'x' (type: Space)
```

... but don't be fooled: it's not a dict!

```
In [4]: 'x' in tags
Out[4]: False
```

When using the `in` keyword, `AxisTags` behaves like a list of `AxisInfo` objects:

```
In [5]: x_tag = tags['x']

In [5]: x_tag in tags
Out[5]: True
```

I think it would be more convenient if `AxisTags` behaved like a dict in all cases.  In particular: `'x' in tags` should do the expected thing, and it would also be nice to add convenience dict methods methods like `tags.keys()` and `tags.values()`.

**Comment by hmeine** [comment]
+1
Sounds totally reasonable to me.

**Comment by ukoethe** [comment]
Originally, `AxisTags` was just array-like, so the behavior was intended. I guess in the meantime we came to like the dict interface better. I changed it as requested in commit bdd199493b57f4dcee5a87a6eece48a7f1591187
