### ISSUE TITLE
In Vigranumpy: Check for key in AxisTags fails if key is of type AxisInfo

### ISSUE THREAD

**Issue by dstoe** [ukoethe/vigra#233]
since commit bdd199493b57f4dcee5a87a6eece48a7f1591187 the following python minimal example fails in the last command due to an "do not match C++ signature" error:
```python
import vigra
tag = vigra.AxisInfo('x')
tags = vigra.AxisTags('xyc')
'x' in tags # returns "True"
tag in tags # fails
```
See dstoe/vigra@72ca4a02ba7bda84ebb93a2f5a05339b5d828bf6 for a proposed fix.

**Comment by ukoethe** [comment]
merged https://github.com/dstoe/vigra/commit/72ca4a02ba7bda84ebb93a2f5a05339b5d828bf6
