### ISSUE TITLE
License problems with "lenna" image set

### ISSUE THREAD

**Issue by danstender** [ukoethe/vigra#253]
I'm maintaining Vigraimpex in Debian for the Debian Science Group. Unfortunately, the "lenna" image set became recognized as being problematic for distributing in a free software context [1]. I know this is the standard example image set of image processing for a long time (the model Lena Söderberg was invited to image processing developer's conferences to meet etc.), however we would have to strip out the images out of the upstream tarball  due to the licensing issue. From our view, if these example and tests images could be replaced by upstream this would the best solution. But I know that this is going to be an extensive task regarding the Vigra tests, so just let me point to that issue.

[1] https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html

**Comment by ukoethe** [comment]
Nice to meet you. What version of VIGRA are you working on? Do you have a patch/pull request?

**Comment by danstender** [comment]
Hi! Debian status is: currently we're working on the transition of replacing Vigra 1.9 with 1.10 in Debian (that already took place in Ubuntu), waiting for the gcc5/libstdc++6 transition to get completed [1]. No patches this time. Saga has been patched, everything goes fine.

[1] https://bugs.debian.org/793044

**Comment by danstender** [comment]
Follow-up: https://bugs.debian.org/794853 (libvigraimpex: non DFSG file in the source package)

**Comment by danstender** [comment]
Further follow-up: https://lists.debian.org/debian-devel/2015/08/msg00090.html
Best,
DS

**Comment by danstender** [comment]
I hoped that this problem would vanished, but it remains for Debian. The images are everywhere in the source package and couldn't be replaced easily in the tests etc. I'm going to fix this problem somehow, we've already discussed it, how. Debian is nitpicky on these issues, I know ...

**Comment by ametzler** [comment]
I do not understand why this was closed - It seems to be still open in GIT. I think most downstreams are working around this with local patches. (checked: Fedora and Debian)
