### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#255]
The last formal release was a couple of years ago. Is there any timeline in mind for when the next release might occur?

**Comment by jakirkham** [comment]
Given the recent addition of Python 3 support and the discussion of deprecating Boost.Thread. I wonder if this commit ( https://github.com/ukoethe/vigra/commit/777f70b872751a3459aa405e294dd60c5227b2d9 ) would be a good place to add a release tag.

**Comment by jakirkham** [comment]
Related ( https://github.com/ukoethe/vigra/pull/322 ).

**Comment by ukoethe** [comment]
Done.
