### ISSUE TITLE
Tests don't succeed with VC14

### ISSUE THREAD

**Issue by hmeine** [ukoethe/vigra#256]
We have been trying prereleases of VC14, and there were always problems with vigra's tests, but I hoped that they would vanish when the compiler becomes less buggy.  Now the final version was released, and the errors with vigra are nearly the only ones that persisted. :-(  So far, I am not sure whether it's a plain bug in VC14, or whether this new compiler just reveals bugs that went unnoticed for a long time, although I would suspect the former to have a higher probability.

The following tests fail with a corrupted heap:
* classifier_speed_comparison
* test_simpleanalysis
* test_convolution
* test_classifier
* test_slic2d

I had a closer look at **classifier_speed_comparison**:
* The problem occurs in the old, deprecated implementation, so it can be much faster reproduced by commenting out the use of the new implementation.
* The crash happens in ArrayVector's destructor. (However, the heap corruption could be caused by something else.)

**Comment by hmeine** [comment]
Running the test with valgrind/memcheck on Linux, which did not report any problems.
Substituting ArrayVector by std::vector in ``random_forest_deprec.hxx`` (and substituting .init() calls with std::fill) fixed the problem in VC14, which supports the suspicion that ArrayVector is the culprit.

**Comment by ukoethe** [comment]
This is well possible. ArrayVector solely exists because the guarantee of consecutive memory was missing in C++ 98. Since this has been fixed in C++ 11, std.:vector can (and probably should) be used everywhere.

**Comment by hmeine** [comment]
That was my impression, too, but would you already accept pull requests doing that change?
Furthermore, shouldn't ArrayVector be bug-free nonetheless?

**Comment by ukoethe** [comment]
> That was my impression, too, but would you already accept pull requests
> doing that change?

Yes.

> Furthermore, shouldn't ArrayVector be bug-free nonetheless?

Good question. How much time should we spend to fix a deprecated class? 
If it is an easy fix, it's probably worthwhile.

**Comment by hmeine** [comment]
My problem is that I see the "easy way out", i.e. replacing the use of ArrayVector with std::vector, but I dislike fixing something without understanding the problems.  We're really only looking at the symptoms here.  On the other hand, the "clean" way of dealing with this could mean spending days or even weeks with Microsofts compiler, only to find a bug that shouldn't have been in there in the first place, that we have to work around anyhow, and may or may not get a fix for in the next year or so.
For a comparatively small institute, we have already found a shocking number of real Microsoft compiler bugs (in particular with -O2), not all of which were properly fixed.  But that's a lot of work. :-(

**Comment by hmeine** [comment]
Maybe we (actually, Wolf) have found the bug:
```c++
template <class T, class Alloc>
inline void
ArrayVector<T, Alloc>::deallocate(pointer data, size_type size)
{
    if(data)
    {
        detail::destroy_n(data, size);
        alloc_.deallocate(data, size);
    }
}
```
The problem is that `alloc_.deallocate` is given the **size**, but that may be different from the **capacity**, i.e. the size of the allocated block.  Many allocators do not need the size for free'ing memory, which is a probable reason why this bug has stayed unnoticed for such a long time.

**Comment by hmeine** [comment]
As far as I can see, we could also merge the regression test from https://github.com/hmeine/vigra/commit/04c8b150673f3acb15f4220be2bce0b81de80399
What do you think, Ulli?

**Comment by ukoethe** [comment]
Yes, please create a PR against branch 'version-1-11-rc'. But check first if someone has already added a similar test manually (and rename the test function).

**Comment by hmeine** [comment]
Argh.  I don't know why I did not see that an hour ago, but above, my commit is even linked to this issue.
I made a mistake, though (forgot to add( testCase( ... )) ), and what would be an appropriate name in your opinion? I would maybe extend it to `testBackInsertionUntilReallocation_failedOnVC14`?

**Comment by hmeine** [comment]
Should I really PR against version-1-11-rc?  Why not against master?

**Comment by ukoethe** [comment]
> what would be an appropriate name

Why not simply `testBackInsertion()`? The code was wrong on all platforms, vc14 just happened to expose it first.

> Why not against master?

'master' is currently frozen (except for your commits). Until the release, all development happens in 'version-1-11-rc'. (BTW, I' still cleaning up the documentation, then the release is ready to go).

**Comment by hmeine** [comment]
Argh. I got two phone calls during this, which left me confused and now pushed to master by accident.  Sorry about that.
`testBackInsertion` already existed. I chose `testBackInsertionUntilReallocation`, which IMO matches the other test names quite well.
Now, shall I do something about the merge with the 1-11-rc branch?
