### ISSUE TITLE
vigra redefines several symbols from boost::graph by default

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#260]
`graphs.hxx` is included by some files which seem (to a user) to have nothing to do with graphs (e.g. `multi_morphology.hxx`).  That's fine, except that vigra's default behavior is to [redefine](https://github.com/ukoethe/vigra/blob/0822c132b4850162e96139b9ba81ddceb1ab8f91/include/vigra/graphs.hxx#L63) certain symbols in the `boost` namespace that prevent the user from using `boost::graph` for her own purposes, unless she knows to set `WITH_BOOST_GRAPH` before including certain vigra headers.

Can the default behavior be changed, so that vigra users don't need to know about this implementation detail?

**Comment by hmeine** [comment]
How would you suggest to do that?  Looking for boost/graph.hpp being included already via the include guards?  I don't see another possibility immediately.

Interestingly the same file [already checks for boost/tuple.hpp being included](https://github.com/ukoethe/vigra/blob/0822c132b4850162e96139b9ba81ddceb1ab8f91/include/vigra/graphs.hxx#L100] in line 100, so that would not be a new pattern...

**Comment by stuarteberg** [comment]
>How would you suggest to do that?

I guess I'm not sure.  I don't know this part of vigra well enough to understand why these symbols must be defined in the `boost` namespace.  Perhaps a new namespace `vigra::graphs` could be defined, and these names could be defined within it?

Something like this:

```c++
#ifdef WITH_BOOST_GRAPH
#  include <boost/tuple/tuple.hpp>
#  include <boost/graph/graph_traits.hpp>
#  include <boost/graph/properties.hpp>

namespace vigra { namespace graphs {
    // Alias the names from boost
    typedef boost::directed_tag directed_tag;
    // ... etc ...
}}

#else

namespace vigra { namespace graphs {
    // Define everything ourselves
    struct directed_tag { };
    // ... etc ...

}}

#endif

```

In all other files, we would need to replace usage of `boost::directed_tag` with `vigra::graphs::directed_tag`.

**Comment by hmeine** [comment]
Another option could be to remove this header file (which is apparently an incomplete boost substitute) and just accept the dependency on boost::graph?

**Comment by ukoethe** [comment]
The goal of this design is to implement the boost-graph API for GridGraph (and possibly other graph classes). Some of the API symbols (such as `directed_tag`) by definition reside in namespace `boost`. Now I wanted the GridGraph class to remain usable via the boost-graph API, even when boost itself is not present. Ideally, C++ would support a conditional depending on file existence:
```c
#if  include_exists(boost/graph/graph_traits.hpp)
    #include <boost/graph/graph_traits.hpp>
#else 
    #include <vigra/boost_api.hxx>
#endif
```
but I'm not aware of how this can be done. Any ideas?

**Comment by stuarteberg** [comment]
>I wanted the GridGraph class to remain usable via the boost-graph API, even when boost itself is not present.

Wouldn't my suggestion above be suitable?  If the user supplies `WITH_BOOST_GRAPH=1`, then `vigra::graphs::directed_tag` would be synonymous with `boost::directed_tag`.  The user would be free to choose whichever spelling she prefers.

>I'm not aware of how this can be done. Any ideas?

I know of no *standard* mechanism.  In clang, this can be achieved with a special macro:
http://clang.llvm.org/docs/LanguageExtensions.html#include-file-checking-macros

It appears that gcc-5 now supports that macro, too, but gcc-4 does not:
https://gcc.gnu.org/gcc-5/changes.html

I don't know of such a mechanism in Visual Studio.

**Comment by stuarteberg** [comment]
To be clear, this isn't a super-high-priority issue.  I don't know what percentage of users include vigra headers and Boost.Graph headers in the same compilation unit, but it's probably not a large percentage.  Under the current scheme, anyone doing so must do a bit of digging to discover the `WITH_BOOST_GRAPH` macro.  It's a little annoying, but it's not a show-stopper.  If fixing it is a huge hassle, then maybe it's not worth it.

**Comment by ukoethe** [comment]
fixed in 8d8ab03736ceca9a4cb8ffb9c403b49090ac74b3 and b209bc9b31efbee8c4df21bde51b581581e49cc1

**Comment by dstoe** [comment]
8d8ab03 and b209bc9 break the test_gridgraph_BGL unittest for me. The concept checking (http://github.com/ukoethe/vigra/blob/master/test/gridgraph/test.cxx#L584-L590) fails, because the expressions required by the concepts need to be available in the global or boost namespace (if I got it right).

Commit 475db63a993c9a38a59e4edff79081ab38e5aaa2 moves all those expressions to the boost namespace.

**Comment by dstoe** [comment]
I accidentially pushed to the master, I'm sorry. I meant to push to my local fork.
