### ISSUE TITLE
Add installation help for libhdf5 support under Ubuntu

### ISSUE THREAD

**Issue by mostlyuseful** [ukoethe/vigra#261]
Ubuntu ships multiple versions of libhdf5: A serial implementation and a parallelized one using OpenMPI. Their include and library directories differ with the implementation.

Under a x64 system, the directories are:

Serial version:
    /usr/include/hdf5/serial/
    /usr/lib/x86_64-linux-gnu/hdf5/serial/
    
MPI version:
    /usr/include/hdf5/openmpi/
    /usr/lib/x86_64-linux-gnu/hdf5/openmpi/
    
Vigra does not correctly detect the libhdf5 location under Ubuntu.

One way to feed the wanted (unparallelized) libhdf5 implementation to vigra is:

> cd $VIGRA_DIR
> mkdir build
> cd build
> cmake -DHDF5_INCLUDE_DIR=/usr/include/hdf5/serial/ -DCMAKE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial/ ..
> make

It would be great to add some words on how to do this to the installation documentation, since I had to refer to the CMakeLists.txt and FindHDF5.cmake on how to handle libhdf5 in non-standard locations.

**Comment by ukoethe** [comment]
Thanks for the report. Current `cmake` comes with a significantly improved [FindHDF5](https://github.com/Kitware/CMake/blob/master/Modules/FindHDF5.cmake) that may already solve your problem. To try it, temporarily rename `$VIGRA_DIR/config/FindHDF5.cmake` (you may have to do this in a frech build directory) adn let me know what happened.

**Comment by ukoethe** [comment]
Fixed in 550dbc2b02278965dff59af7cb829f0a3baec0da
