### ISSUE TITLE
noexcept(false) for InitProxy::~InitProxy()

### ISSUE THREAD

**Issue by mmuellner** [ukoethe/vigra#263]
I had to add `noexcept(false)` to `InitProxy::~InitProxy()` when using Microsoft Visual C++ 2015. This is because of the [implicit `noexcept` for destructors since C++11](http://denisbider.blogspot.co.at/2015/07/exceptions-in-destructors-and-visual.html). It might be a good idea to add this for other compilers too.

```diff
diff --git a/include/vigra/separableconvolution.hxx b/include/vigra/separableconvolution.hxx
index 3ae5781..853cbf9 100644
--- a/include/vigra/separableconvolution.hxx
+++ b/include/vigra/separableconvolution.hxx
@@ -1411,6 +1411,8 @@ class Kernel1D
         ~InitProxy() 
 #ifndef _MSC_VER
              throw(PreconditionViolation)
+#elif _MSC_VER >= 1900
+             noexcept(false)
 #endif
         {
             vigra_precondition(count_ == 1 || count_ == sum_,
```

**Comment by ukoethe** [comment]
For modern compilers, the entire proxy trick should be replaced with an initializer_list or variadic templates.
