### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#268]
Fortunately, Guido punted this necessary move from 2015 to 2020. ( https://hg.python.org/peps/rev/76d43e52d978 ) However, at some point, this move will need to occur. If this is very complex, it may be worth trying to understand what makes it complex and what it will take to remedy it. Already some packages don't support Python 2.x.

**Comment by ukoethe** [comment]
The problem with Python 3 is that it introduces incompatibilities without offering matching benefits. Had Python 3 solved a real problem (e.g. removed the Global Interpreter Lock), everyone would have switched right away. But I've read several "Why Python 3 is great" presentations and found them all lame. Even after 7 years of Python 3 development, I see no compelling technical reason to switch, only social pressure.Guido thoroughly messed this up ...

Having said this,we should nonetheless give in to the social pressure. I don't think it will be too difficult.

**Comment by hmeine** [comment]
A good intermediate step that is commonly chosen is to drop support for versions <= 2.5.  Then, it is often possible to achieve compatibility with both major versions in the same codebase.
BTW: I think personally blaming people is not necessary here. It is hard to change a language that's already so widely used, and Python 3 is certainly cleaner in many respects.

**Comment by ukoethe** [comment]
The slow rate of adoption clearly proves me right. I don't think that all those people are just lazy.

**Comment by jakirkham** [comment]
I agree that Python 3 is generally overwhelming considering it is a breaking change and I have my own issues with it. All that aside, it is here and at some point it will be all that is left.

So, I have a good idea of what changes to expect from the Python side, but are there changes with regards to Boost.Python that will need to be taken into account?

**Comment by ukoethe** [comment]
Rainer Herzog, a former student of mine, started a port two years ago, but then got stuck halfway. His changes are in https://github.com/hzg1/vigra/tree/overlay-viewer. I think Rainer stopped when he couldn't fix the call
```c++
pyaxistags.permutationToNormalOrder()
```
(in `vigra/vigranumpy/src/core/converters.cxx#constructArrayFromAxistags()`). This function calls back into Python and raised a TypeError instead of returning the desired permutation.

**Comment by ukoethe** [comment]
Please watch progress in Python 3 conversion in PR https://github.com/ukoethe/vigra/pull/277

**Comment by jakirkham** [comment]
Yeah, I saw this recently. Looks interesting.

**Comment by jakirkham** [comment]
It appears that this is basically done with CI on Linux. Not sure if there needs to be CI for Windows with Python 3. Some work was done for adding CI on Mac ( https://github.com/ukoethe/vigra/pull/303 ). However, this ran into issues with some linking errors. At present, I can't continue it, but if someone would like to give it a try, they are more than welcome to.

**Comment by ukoethe** [comment]
> Not sure if there needs to be CI for Windows with Python 3.

My plan is to install the necessary dependencies via conda. It seems that AppVeyor and conda both support Visual Studio 2015. The only missing package is a compatible boost_python, which we can easily supply from our own channel. So this looks easy.

**Comment by jakirkham** [comment]
Should we just switch everything to conda then?

**Comment by ukoethe** [comment]
For now, I only want to use conda for the Appveyor build (which doesn't yet test vigranumpy at all), and postpone a decision about switching everything until after the conda folks fixed the features stuff.

**Comment by jakirkham** [comment]
This is now complete. :tada:
