### ISSUE TITLE
Segfault in extractRegionFeatures

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#327]
The following program segfaults on my machine.  Presumably, the problem is related to the fact that I'm passing in a 1-pixel-wide image.  (I'm using today's master branch, 777f70b)

```python
import numpy as np
import vigra
values = np.arange(1000, dtype=np.float32)[None] # Add singleton dimension with [None]
labels = np.arange(1000, dtype=np.uint32)[None]
acc = vigra.analysis.extractRegionFeatures(values, labels) #
```

I'm interested in using `extractRegionFeatures()` with (labeled) 1D data.  (I don't need coordinate-based features.)  I thought adding a singleton dimension as shown above would do the trick, but apparently that doesn't quite work. Is there a recommended way to process 1D data?

**Comment by stuarteberg** [comment]
Update: The crash seems to be related to my use of `[None]` to prepend a singleton axis on the arrays.  This program **does not** segfault:

```python
import numpy as np
import vigra
values = np.arange(1000, dtype=np.float32).reshape(1,1000)
labels = np.arange(1000, dtype=np.uint32).reshape(1,1000)

acc = vigra.analysis.extractRegionFeatures(values[0][None], labels)
```

But this program **does** segfault:

```python
import numpy as np
import vigra
values = np.arange(1000, dtype=np.float32).reshape(1,1000)
labels = np.arange(1000, dtype=np.uint32).reshape(1,1000)

acc = vigra.analysis.extractRegionFeatures(values, labels[0][None])
```

It turns out that the `[None]` syntax results in different strides than `reshape` produces:

```python
In [10]: print labels.shape, labels.strides, labels.flags.c_contiguous
(1, 1000) (4000, 4) True

In [11]: print labels[0][None].shape, labels[0][None].strides, labels[0][None].flags.c_contiguous
(1, 1000) (0, 4) False
```

I'm not sure why numpy inserts a `0` for the first stride, nor do I understand why that `0` causes it to be non-c-contiguous.

**Comment by jakirkham** [comment]
What version of NumPy?

**Comment by stuarteberg** [comment]
>What version of NumPy?

 1.9

**Comment by jakirkham** [comment]
So, turns out that is an old NumPy issue ( https://github.com/numpy/numpy/issues/1673 ).

**Comment by jakirkham** [comment]
IIRC you could build NumPy with `NPY_RELAXED_STRIDE_CHECKING`, which should change that behavior. At some point, that will go in. I believe 1.12.0.

**Comment by ukoethe** [comment]
When I experimented with singleton axes in VIGRA, I came to the conclusion that stride 0 is not a good idea. I might be able to fix the problem by replacing the stride with a more sensible value when creating the `MultiArrayView`.
