### ISSUE TITLE
defaultAxistags() has inconvenient defaults

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#331]
I think it's typical not to transpose a large array in numpy after creating it, and numpy uses C-order indexing by default.  But when such an array is passed into a vigra C++ function, vigra needs to guess what order it is in.  The guessed order is chosen by [`defaultAxistags()`](http://ukoethe.github.io/vigra/doc-release/vigranumpy/index.html#vigra.VigraArray.defaultAxistags).  For example:

```python
>>> vigra.VigraArray.defaultAxistags(3, noChannels=True)
x y z
```

For a typical user, the above order is exactly wrong.  Even if the user doesn't care about the semantics (e.g. a gaussian filter will look the same no matter how you name the axes), the performance may suffer considerably.

While this is not a new issue per se, it was brought to my attention today while implementing #330.  In that case, the performance difference between the default xyz order and the manually-tagged zyx order is more than 10x.

So, in the interest of helping users who don't always have the discipline to tag their arrays with axistags before calling vigra functions (guilty here), I propose that we should assume that untagged arrays are probably in C-order, and the default tags should be chosen accordingly.  Do you think that will be a severely disruptive change?

**Comment by ukoethe** [comment]
`defaultAxistags()` offers the `order` argument to avoid guessing the order. However, the preferred function to add axistags is `vigra.taggedView()`. If neither `axistags` nor `order` are provided to this function, it currently assumes vigra order, which is indeed not the most sensible default. I think the best default choice is to assign tags `cxyzt` or `xyzt` (depending on the `noChannels` parameter) in ascending order of strides.

**Comment by stuarteberg** [comment]
>the preferred function to add axistags is `vigra.taggedView()`.

Indeed, that's what I typically use.

>If neither `axistags` nor `order` are provided to this function, it currently assumes vigra order, which is indeed not the most sensible default.

Yeah, just to restate the issue with a more concrete example, we should aim to help naive (or lazy) users would might typically write something like this:

```python
In [33]: a = np.random.random((200,200,200)).astype(np.float32)

In [34]: %timeit feats = vigra.analysis.extractFeatures(a, features=['sum', 'mean'])
10 loops, best of 3: 72.9 ms per loop
```

Whoops, we forgot to use `taggedView()`.  Look what happens when we add it:

```python
In [35]: %timeit feats = vigra.analysis.extractFeatures(vigra.taggedView(a, 'zyx'), features=['sum', 'mean'])
10 loops, best of 3: 48.4 ms per loop
```

>I think the best default choice is to assign tags `cxyzt` or `xyzt` (depending on the `noChannels` parameter) in ascending order of strides.

Relying on the strides to determine the default order is an attractive idea because it will likely result in the best performance in the case when the spatial axes are interchangeable.  But I'm afraid it might be confusing to some users.  I think just assuming that the array is in `tzyxc` order is more straightforward (and seems more numpy-like), and likely enough to be correct.

**Comment by ukoethe** [comment]
How about changing `arraytypes.py` line 212 into:
```
        if not axistags:
            if not order:
                order = 'C'
            axistags = VigraArray.defaultAxistags(array.ndim, order, noChannels)
```

**Comment by stuarteberg** [comment]
I'm hoping that users who never even call `taggedView()` at all will get better performance in the default case (i.e. for C-order number arrays).  In the `extractFeatures()` example shown above, I think `taggedView()` is never called (even under the hood), so your proposal won't make a difference.

**Comment by ukoethe** [comment]
VIGRA will never automatically transpose an array without axistags, it is too dangerous. If you pass in a C-order array, you must call `taggedView()` or live with the performance penalty. I'll attempt to implement automatic loop order optimization in VIGRA 2.

**Comment by stuarteberg** [comment]
>VIGRA will never automatically transpose an array without axistags, it is too dangerous.

I don' think "transpose" is the right word here.  When given an untagged array from a Python user, vigra has no choice but to choose *some* axis semantics.  There's just no way to avoid the question.  Doing "nothing" is still a choice (even if it's implicit).  Right now, vigra apparently chooses to interpret the array as if it is in 'F' order.  I'm merely pointing out that 'C' order is a more appropriate choice, given that numpy uses C-order by default.

**Comment by ukoethe** [comment]
Consider the gradient: it computes a 3-channel volume from a scalar volume. How shall the channels be sorted? The current rule is: When axistags are present, the gradient vector is stored in 'xyz' order. When no axistags are present, the gradient is stored in the same order as the array indices. Your suggestion would change this convention, such that the gradient elements would be stored in reverse index order (unless VIGRA's gradient algorithm wouöld be changed accordingly). 

I think the fundamental mismatch between VIGRA's F-order and numpy's C-order cannot be resolved by changing the default behavior -- axistags are meant to make the semantics explicit.

**Comment by stuarteberg** [comment]
OK, I was worried there might be some problem like that.  It's nice to have a concrete example.

Still, the whole C-order vs. F-order vs. V-order subject is tricky for users to master, despite your nice writeup in the vigranumpy docs.  The problem isn't going to disappar (we'll always need axistags), but maybe if Vigra 2.0 switches to C-order by default, there will be at least 1 less detail to keep track of.

**Comment by ukoethe** [comment]
The plan for VIGRA 2 is to have the user choose the order in the constructor (with suitable defaults), and to have the algorithms optimize themselves according to whatever order is passed in.
