### ISSUE TITLE
Signature of VigraArray.reshape() doesn't match numpy.ndarray.reshape()

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#338]
The `VigraArray` implementation of `reshape()` matches the [numpy docs](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.reshape.html#numpy.reshape), but -- annoyingly -- the numpy docs are wrong.

I guess it would be nice if `VigraArray` mimics `numpy.ndarray`, even when `ndarray` doesn't match it's own documentation.  Otherwise, it's easy to accidentally write code that works for `ndarray`s, but doesn't accept `VigraArray`s.

The specific discrepancy is that `numpy.reshape()` can accept the `shape` as a tuple OR as an argument list.  Furthermore, if `order` is provided, it MUST be provided as a keyword argument.

~~I guess the proper signature should be something like this:~~ (wait, this isn't right...)

```python
def reshape(*shape, order='C'):
    if not isinstance(shape, collections.Iterable):
        shape = (shape,)
    ...
```

Vigra and numpy  behave the same for these calls:

```python
In [62]: a = np.ones((10,3))

In [63]: v = vigra.taggedView(a, 'yx')

In [64]: a.reshape((5,6), order='C').shape
Out[64]: (5, 6)

In [65]: v.reshape((5,6), order='C').shape
Out[65]: (5, 6)
```

But they have different behavior for these calls:

```python
In [67]: a.reshape(5,6, order='C').shape
Out[67]: (5, 6)

In [68]: v.reshape(5,6, order='C').shape
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-68-86168054e953> in <module>()
----> 1 v.reshape(5,6, order='C').shape

TypeError: reshape() got multiple values for keyword argument 'order'
```

and also different behavior for these calls:

```python
In [69]: a.reshape((5,6), 'C').shape
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-69-ae2c5a6357ed> in <module>()
----> 1 a.reshape((5,6), 'C').shape

TypeError: an integer is required

In [70]: v.reshape((5,6), 'C').shape
Out[70]: (5, 6)
```

**Comment by ukoethe** [comment]
I thought about your suggestion but am reluctant to the change for these reasons:

1. Since the alternative syntax is not documented, it is essentially undefined behavior that just happens to work.
2. They used C to implement `order` as a keyword-only argument (contrary to documentation). Emulating this behavior in Python 2 is ugly and leads to a confusing function signature and corresponding auto-generated documentation.

Is the change important for something?

**Comment by stuarteberg** [comment]
Fair enough.

>Is the change important for something?

No, not really.  I was just surprised recently when some of my code was working in my tests, but not in a real-world case.  It turns out my test used `ndarray` but the real-world case used `VigraArray`.  But now that I know about this issue, it's easy to just search for all instances of `reshape()` and fix them.

**Comment by ukoethe** [comment]
Thanks. While we are at it, can you check if https://github.com/ukoethe/vigra/issues/245 can be closed as well?

**Comment by hmeine** [comment]
Personally, I find it very convenient to be able to leave out the extra () when calling reshape(), and I got used to it.  I think I saw quite some code using reshape with multiple arguments.  I do agree that it is not a very clean API, though.
