### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [ukoethe/vigra#360]
Would you like to [replace any double quotes](https://github.com/ukoethe/vigra/blob/799e799f431c417c5fe8c479fb9a16c7e3d3b5e9/include/vigra/threadpool.hxx#L43 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by ukoethe** [comment]
Certainly not. The double quotes are there precisely for of the semantics you cross-referenced above.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by ukoethe** [comment]
Are you suggesting that I don't know what I'm doing?

The includes in quotes are supposed to be taken from the same directory to avoid possible conflicts between a local and system installation of VIGRA. The intended behavior is implemented by all compilers I care about. If you present a concrete example where the current implementation fails, I might reconsider my decision.

**Comment by elfring** [comment]
>Are you suggesting that I don't know what I'm doing?

Maybe partly in this use case.

There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?

**Comment by ukoethe** [comment]
> > Are you suggesting that I don't know what I'm doing?

> Maybe partly in this use case.

Mind your words before you have demonstrated your capabilities in constructive contributions.

**Comment by elfring** [comment]
I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories. Can such a security detail become a bit more important occasionally?

**Comment by ukoethe** [comment]
> I would generally prefer to exclude the potential for the inclusion of header files from unexpected directories.

This concern doesn't apply here, because all quoted includes are in the same directory, as you can easily verify for yourself. If you find an instance where this is not the case, it would be a bug that I'll correct.

**Comment by elfring** [comment]
Would you like to support the use case that your header files should occasionally only be found from the installed system directories?

**Comment by ukoethe** [comment]
This has nothing to do with the present discussion. The quotes are there to make sure that once you picked a header from a particular directory (system or otherwise), all other headers are taken from the same directory.

**Comment by elfring** [comment]
Your library can also be installed as it is usual with other software.
* Can any conflicts and version mismatches happen if the inclusion style will trigger the reuse of header files from other storage locations?
* When do you want to choose between inclusion from "blessed" directories instead of a random and "convenient" folder?
