### ISSUE TITLE
appveyor build with hdf5-1.8.16 failes

### ISSUE THREAD

**Issue by kkiefer** [ukoethe/vigra#369]
The appveyor build with the environment : PY_VERSION=3.5, VC_VERSION=14 failed with a clone of the current vigra master branch, due to the linker error LNK2019 (line 2502 - 2505 in the attached log).
This is also true for the latest two pull requests.
In either case hdf5-1.8.16 was used, which is not true for any appveyor builds in previous pull requests.

[appveyor_test_log.txt](https://github.com/ukoethe/vigra/files/257814/appveyor_test_log.txt)

**Comment by ukoethe** [comment]
It seems that hdf5 1.8.16 is incompatible with the current VIGRA. For the time being, we can simply have conda pin the hdf5 version to 1.8.15.1. Please edit `appveyor.yml`like this:
```
    - if "%PY_VERSION%" == "3.5" conda create -q --yes -n python python=%PY_VERSION% jpeg libpng libtiff hdf5=1.8.15.1 numpy nose
```

**Comment by kkiefer** [comment]
Done (pr #370). Shall we leave this issue open until hdf5-1.8.16 compatibility is established?

**Comment by ukoethe** [comment]
Yes.

**Comment by ukoethe** [comment]
The problem is caused by the conda package for HDF5 1.8.16, see bug report at https://github.com/conda/conda/issues/2614

**Comment by mcg1969** [comment]
Issue moved here: https://github.com/ContinuumIO/anaconda-issues/issues/811

**Comment by ukoethe** [comment]
I recommend downloading dependencies from conda-forge.
