### ISSUE TITLE
cmake: automatically activate '-std=c++11' when needed.

### ISSUE THREAD

**Issue by leenachennuru** [ukoethe/vigra#381]
I have been getting compilation errors if I try to include the numpy array converters file. The error message is as follows. Does anyone else have he same issue ? 

In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:180:29: error: a space is
      required between consecutive right angle brackets (use '> >')
struct TypeName<Singleband<T>>
                            ^~
                            > >
/opt/local/include/vigra/numpy_array_converters.hxx:185:28: error: a space is
      required between consecutive right angle brackets (use '> >')
struct TypeName<Multiband<T>>
                           ^~
                           > >
/opt/local/include/vigra/numpy_array_converters.hxx:191:1: error: expected
      expression
: public TypeName<T>
^
/opt/local/include/vigra/numpy_array_converters.hxx:192:1: error: expected a
      type
{};
^
/opt/local/include/vigra/numpy_array_converters.hxx:766:26: error: expected
      expression
            raw_function([msg](tuple, dict) -> object {
                         ^
/opt/local/include/vigra/numpy_array_converters.hxx:814:19: error: too many
      arguments provided to function-like macro invocation
                  "def(): use multidef() to export multiple overloads.");
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:583:9: note: 
      macro 'static_assert' defined here
# define static_assert(__b, __m) \

```
    ^
```

In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:813:5: error: use of
      undeclared identifier 'static_assert'; did you mean 'staticAssert'?
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value, 
    ^~~~~~~~~~~~~
    staticAssert
/opt/local/include/vigra/static_assert.hxx:46:11: note: 'staticAssert' declared
      here
namespace staticAssert {
          ^
In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:813:5: error: unexpected
      namespace name 'staticAssert': expected expression
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value, 
    ^
/opt/local/include/vigra/numpy_array_converters.hxx:823:19: error: too many
      arguments provided to function-like macro invocation
                  "def(): use multidef() to export multiple overloads.");
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:583:9: note: 
      macro 'static_assert' defined here
# define static_assert(__b, __m) \

```
    ^
```

In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:822:5: error: use of
      undeclared identifier 'static_assert'; did you mean 'staticAssert'?
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value,
    ^~~~~~~~~~~~~
    staticAssert
/opt/local/include/vigra/static_assert.hxx:46:11: note: 'staticAssert' declared
      here
namespace staticAssert {
          ^
In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:822:5: error: unexpected
      namespace name 'staticAssert': expected expression
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value,
    ^
/opt/local/include/vigra/numpy_array_converters.hxx:832:19: error: too many
      arguments provided to function-like macro invocation
                  "def(): use multidef() to export multiple overloads.");
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:583:9: note: 
      macro 'static_assert' defined here
# define static_assert(__b, __m) \

```
    ^
```

In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:831:5: error: use of
      undeclared identifier 'static_assert'; did you mean 'staticAssert'?
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value,
    ^~~~~~~~~~~~~
    staticAssert
/opt/local/include/vigra/static_assert.hxx:46:11: note: 'staticAssert' declared
      here
namespace staticAssert {
          ^
In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:831:5: error: unexpected
      namespace name 'staticAssert': expected expression
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value,
    ^
/opt/local/include/vigra/numpy_array_converters.hxx:841:19: error: too many
      arguments provided to function-like macro invocation
                  "def(): use multidef() to export multiple overloads.");
                  ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:583:9: note: 
      macro 'static_assert' defined here
# define static_assert(__b, __m) \

```
    ^
```

In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:840:5: error: use of
      undeclared identifier 'static_assert'; did you mean 'staticAssert'?
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value,
    ^~~~~~~~~~~~~
    staticAssert
/opt/local/include/vigra/static_assert.hxx:46:11: note: 'staticAssert' declared
      here
namespace staticAssert {
          ^
In file included from armavnmodule.cpp:17:
/opt/local/include/vigra/numpy_array_converters.hxx:840:5: error: unexpected
      namespace name 'staticAssert': expected expression
    static_assert(!std::is_base_of<PythonMultidefFunctor, Functor>::value,
    ^
17 errors generated.
make: **\* [armavnmodule.o] Error 1

**Comment by leenthegenieass** [comment]
I figured out the problem. This library needs the C ++ 2011 compiler which and specifying that with the compiler options in the Makefile will resolve this issue.

**Comment by ukoethe** [comment]
I guess our cmake scripts don't always activate the '-std=c++11' flag when they should. I renamed the issue accordingly.

**Comment by emmenlau** [comment]
This should be fixed in our latest changes (see my correpsonding PR).
