### ISSUE TITLE
Vigra not finding OpenEXR

### ISSUE THREAD

**Issue by slackhead** [ukoethe/vigra#383]
Hi
I'm trying to build vigra 1.11.0 on slackware64 14.2 and I can't get it to see OpenEXR. This is what I'm doing:

  cmake \ 
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS -I/usr/include/OpenEXR" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS -I/usr/include/OpenEXR" \ 
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
    -DWITH_OPENEXR=ON \
    -DCMAKE_BUILD_TYPE=Release .. 

It still says that it can't find it. Any help would be great.

**Comment by ukoethe** [comment]
Hi,

after running cmake from the command line, you should open the cmake GUI 
(via `ccmake`or `cmake-gui`) and find entries referring to OpenEXR. If 
the information was not found, the value of those entries should contain 
the string "NOTFOUND". Replace these values with the correct ones and 
re-configure. This should solve the problem.

Best
Ulli

Am 20.07.2016 um 07:15 schrieb Slackhead:

**Comment by slackhead** [comment]
I've already tried. There is only one option for OpenEXR:
WITH_OPENEXR OFF
Turning it on does nothing.

**Comment by slackhead** [comment]
Found it: These paths show in cmake:
-DOPENEXR_IEX_LIBRARY=/usr/include/OpenEXR \
-DOPENEXR_IMATH_LIBRARY=/usr/include/OpenEXR \
-DOPENEXR_ILMTHREAD_LIBRARY=/usr/include/OpenEXR \

I don't know why ccmake didn't see them.
