### ISSUE TITLE
Compile tests with mingw-w64 gcc-6.1.0 on Windows fails due to dllimport error

### ISSUE THREAD

**Issue by emmenlau** [ukoethe/vigra#388]
I'm trying to compile vigra 1.11.0 on Windows mingw-w64 with gcc-6.1.0 using cmake. The compile works, but compiling tests with "make check" fails with the following error:

```
[ 19%] Linking CXX executable test_counting_iterator.exe
In file included from C:/msys2/tmp/mingw-w64-vigra/src/build-x86_64-w64-mingw32/include/vigra/random_forest/rf_visitors.hxx:39:0,
                 from C:/msys2/tmp/mingw-w64-vigra/src/build-x86_64-w64-mingw32/include/vigra/random_forest/rf_decisionTree.hxx:53,
                 from C:/msys2/tmp/mingw-w64-vigra/src/build-x86_64-w64-mingw32/include/vigra/random_forest.hxx:56,
                 from C:/msys2/tmp/mingw-w64-vigra/src/build-x86_64-w64-mingw32/test/classifier/speed_comparison.cxx:7:
C:/msys2/tmp/mingw-w64-vigra/src/build-x86_64-w64-mingw32/include/vigra/hdf5impex.hxx:712:47: error: function 'const vigra::ArrayVector<long long unsigned int>& vigra::HDF5ImportInfo::shape() const' definition is marked dllimport
     VIGRA_EXPORT ArrayVector<hsize_t> const & shape() const
```

Can you help me if this is a known issue or how to address it?

**Comment by emmenlau** [comment]
I think the following patch would solve this issue:
[0002-vigra-dllexport.txt](https://github.com/ukoethe/vigra/files/614486/0002-vigra-dllexport.txt)

**Comment by emmenlau** [comment]
This issue is now open since August last year. Would someone be willing to review my small patch and possibly include it in vigra?

**Comment by ukoethe** [comment]
Sorry, this got lost because the patch was not submitted as a pull request. I created PR https://github.com/ukoethe/vigra/pull/401 and will merge as soon as the tests got through.

**Comment by emmenlau** [comment]
Awesome, thanks! Then the next release will compile natively on MSYS2 and MINGW.

**Comment by emmenlau** [comment]
Thanks for applying!
