### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by ilovezfs** [ukoethe/vigra#404]
While working on the hdf5-1.10.0-patch1 upgrade for Homebrew, I noticed that vigra 1.11.0 doesn't build against the new hdf5 but that the HEAD of master at ee6b17e does. Any chance of getting a new release tag for vigra so that we don't have issues when revision bumping it as part of the hdf5 upgrade process?

**Comment by iMichka** [comment]
We will tag it as `vigra 1.11.0.1-alpha1` the time being (so that it builds with the new hdf5), and does not block all the other reverse dependencies.
See https://github.com/Homebrew/homebrew-science/pull/5026

**Comment by ilovezfs** [comment]
ping

**Comment by ukoethe** [comment]
Thanks for pointing this out. I can make release `1.11.1` as soon as I have time (creating and testing the release and documentation takes a bit). If you want to go ahead before that, the recommended release number according to the Conda/Python versioning scheme is `1.11.0post1`.

**Comment by ilovezfs** [comment]
Thank you!

**Comment by ilovezfs** [comment]
Any updates here?

**Comment by ukoethe** [comment]
I just released version 1.11.1.

**Comment by ilovezfs** [comment]
Thanks @ukoethe
