### ISSUE TITLE
Building on Windows with Boost 1.64 and Python 3

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#410]
In Boost 1.64, the `boost_python` library got a major version suffix. Namely `boost_python3` for Python 3. AFAICT VIGRA seems able to detect the [correct library name]( https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.3/job/afj486ikt3dyd6tp#L465 ) for `boost_python`. However, it seems to try and link to the wrong name [later on]( https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.3/job/afj486ikt3dyd6tp#L665 ). I'm not entirely sure why this is happening as the search path does what I would [expect]( https://github.com/ukoethe/vigra/blob/Version-1-11-0/CMakeLists.txt#L182 ) it to do. Yet it is clear it is getting messed up later on. Any thoughts on what is going on?

**Comment by ukoethe** [comment]
I suspect the boost folks forgot to upgrade
```
#define BOOST_LIB_NAME boost_python
```
in `boost/python/detail/config.hpp`. Thus, autolinking still looks for the old name.

Am 10. Juni 2017 03:09:20 MESZ schrieb jakirkham <notifications@github.com>:
>In Boost 1.64, the `boost_python` library got a major version suffix.
>Namely `boost_python3` for Python 3. AFAICT VIGRA seems able to detect
>the [correct library name](
>https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.3/job/afj486ikt3dyd6tp#L465
>) for `boost_python`. However, it seems to try and link to the wrong
>name [later on](
>https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.3/job/afj486ikt3dyd6tp#L665
>). I'm not entirely sure why this is happening as the search path does
>what I would [expect](
>https://github.com/ukoethe/vigra/blob/Version-1-11-0/CMakeLists.txt#L182
>) it to do. Yet it is clear it is getting messed up later on. Any
>thoughts on what is going on?

**Comment by ukoethe** [comment]
The #define should read
```
#if PY_MAJOR_VERSION < 3
# define BOOST_LIB_NAME boost_python
#else
# define BOOST_LIB_NAME boost_python3
#endif
```


Am 10. Juni 2017 03:09:20 MESZ schrieb jakirkham <notifications@github.com>:

**Comment by jakirkham** [comment]
That seems likely. Looks like there is another issue upstream that looks basically the same as this (with a slightly different error message). ( https://github.com/boostorg/python/issues/127 ) Will add this suggestion there.

**Comment by jakirkham** [comment]
Yep, patching that header file seems to be helping. Going to close this as it is an upstream issue.

Fixed a couple other build issues on the way. Now am stuck on a different build issue ( https://github.com/ukoethe/vigra/issues/411 ).

**Comment by jakirkham** [comment]
FYI that patch has been accepted upstream.
