### ISSUE TITLE
Linking error with vigranumpy on Windows

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#411]
Running into some sort of [linking error]( https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.13/job/kd0o2sia60x22ktp#L628 ) on Windows. Looks like it is related to `vigranumpy` and the HDF5 interface. It seems to be finding all the [HDF5 libraries]( https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.13/job/kd0o2sia60x22ktp#L489 ) fine. Not entirely sure what is causing the issue.

**Comment by jakirkham** [comment]
Perhaps [this]( https://msdn.microsoft.com/vs-knownissues/vs2015-update3#other-issues ) is relevant, which came up in this [issue]( https://github.com/alecthomas/entityx_python/issues/4 ) where a similar problem was encountered.

**Comment by ukoethe** [comment]
We've observed and investigted this same problem just last week and also came to the conclusion that it is a comiler bug in Visual Studio 2015. It seems that the compiler fails to match the template function `get_pointer` at line 21 of `boost/get_pointer.hpp`. The easiest workaround is to declare that template `inline`. However, this fix must be implemented upstream and doesn't work for existing boost versions. Alternatively, we can provide explicit specializations for all missing variants in vigra itself. A student is preparig a PR on this.

**Comment by jakirkham** [comment]
> It seems that the compiler fails to match the template function `get_pointer` at line 21 of `boost/get_pointer.hpp`. The easiest workaround is to declare that template `inline`.

Yeah I tried patching Boost at that point, but it doesn't appear to have an [effect]( https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.18/job/hd34k5jrjqh926h8#L638 ).

> Alternatively, we can provide explicit specializations for all missing variants in vigra itself. A student is preparig a PR on this.

This sounds good. Maybe I'll wait and see how that goes.

**Comment by ukoethe** [comment]
I created PR https://github.com/ukoethe/vigra/pull/412 to implement the work-around mentioned. Please try if it resolves your problem.

**Comment by jakirkham** [comment]
Thanks. Looks like it built through. 🎉

Though one of the Python tests is failing and I'm not sure why. Is there some sort of verbose mode we can enable? Also please let me know if you would rather I open a new issue or not.

ref: https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.22/job/gcdyyh05xr0tm1jk

**Comment by ukoethe** [comment]
I'm confused -- I don't see a failing test in your link. Once you confirm that the PR resolves your issue, I'll merge merge it and consider the problem fixed. What new issue would you like to open?

**Comment by jakirkham** [comment]
Yeah, looks like that AppVeyor log got cut short for some reason, which was part of the confusion. Perhaps it is the same as this failure (log linked below). If so, I think this is a totally different issue.

ref: https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.22/job/n0p01n2ydnq4xqwb

**Comment by ukoethe** [comment]
Yeah, this looks pretty much unrelated.

**Comment by ukoethe** [comment]
Fixed by #412.

**Comment by jakirkham** [comment]
Raised the test problem as issue ( https://github.com/ukoethe/vigra/issues/413 ).

**Comment by jakirkham** [comment]
Linking this [SO answer]( https://stackoverflow.com/a/38291152 ) for historic relevance.
