### ISSUE TITLE
Test failure in vigranumpy

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#413]
```python
======================================================================
ERROR: Failure: ImportError (No module named 'Release')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\bld\vigra_1497284636422\_b_env\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\bld\vigra_1497284636422\_b_env\lib\site-packages\nose\loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "C:\bld\vigra_1497284636422\_b_env\lib\site-packages\nose\util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
ImportError: No module named 'Release'
----------------------------------------------------------------------
Ran 89 tests in 8.939s
```

ref: https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.22/job/n0p01n2ydnq4xqwb#L924

**Comment by jakirkham** [comment]
My best guess is this has something to do with how things work on these [lines]( https://github.com/ukoethe/vigra/blob/Version-1-11-1/vigranumpy/test/set_paths.py.in#L43-L44 ). Right now I'm creating the directory `build_Release` to perform the CMake build in. Maybe I can workaround it by using `build` as the build directory.

Still it would be nice if the former worked as it looks like it might become a pattern in conda-forge both to workaround issues causes by Google's use of the `BUILD` file for Bazel and to distinguish Release and Debug builds on Windows.

**Comment by jakirkham** [comment]
It doesn't seem to have anything to do with the build directory name (have already switched to `build`). Stumped as to what could be going wrong.

ref: https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.26/job/wna6ykrh30x2gpev

**Comment by ukoethe** [comment]
I've never seen an error like this. The strange thing about it is that `test_segmentation.py` only contains five tests, but the failure is reported on the sixth one, which is not supposed to exist at all. Can you find out what code `nose` is actually trying to execute here?

**Comment by ukoethe** [comment]
I was able to partly reproduce the error: when I execute
```
nosetests  .  testRelease
```
I get the output
```
.....E
======================================================================
ERROR: Failure: ImportError (No module named 'testRelease')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\conda3\envs\python3\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\conda3\envs\python3\lib\site-packages\nose\loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "C:\conda3\envs\python3\lib\site-packages\nose\util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
ImportError: No module named 'testRelease'
```
Not exactly what you see, but it seems that something creeps into the list of tests.

**Comment by jakirkham** [comment]
Looks like this [line]( https://github.com/ukoethe/vigra/blob/Version-1-11-1/vigranumpy/test/CMakeLists.txt#L137 ) might be the issue. Have added a PR ( https://github.com/ukoethe/vigra/pull/416 ) to remove it. With that change, the build [passes]( https://ci.appveyor.com/project/jakirkham/vigra-feedstock/build/1.0.30/job/ifjdjsmfticx361u ). Still waiting for the rest of the builds to complete, but am hopeful they will pass as well.

**Comment by jakirkham** [comment]
Have added a better fix in PR ( https://github.com/ukoethe/vigra/pull/417 ), which seems to work with Visual Studio and NMake.
