### ISSUE TITLE
Failed initialization of vigra::MultiArray when using an rvalue TinyVector that has been initialized with an lvalue integer.

### ISSUE THREAD

**Issue by emmenlau** [ukoethe/vigra#435]
There is a bug in vigra that breaks the correct initialization of a `vigra::MultiArray` when using an rvalue `vigra::TinyVector<long, 1>(return type of shape)` that has been initialized with an lvalue integer.

Please check the corresponding PR #434 to see a live example of the issue. The PR adds a new, failing test that shows the problem. It uses the following (correct) code to construct an ill-sized `vigra::MultiArray lvMA1`:
```
        int width = 15;
        auto lvSh1 = Shape1(width);
        auto rvSh1 = Shape1(15);
        auto lvMA1 = MultiArray<1,double>(lvSh1);
        auto rvMA1 = MultiArray<1,double>(rvSh1);
        auto lvMA2 = MultiArray<1,double>(Shape1(width));
        auto rvMA2 = MultiArray<1,double>(Shape1(15));
```
The MultiArray `lvMA1` is initialized incorrectly due to the use of `lvSh1`. In the same test, the other MultiArrays `rvSh1`, `rvSh1`, `lvMA1`, ... are initialized correctly. So the problem seems to come from the use of `auto lvSh1 = Shape1(width);` (non-working) compared to `auto rvSh1 = Shape1(15);` (working).

This problem has been observed with gcc7 on Ubuntu 18.04 x86_64.

**Comment by ukoethe** [comment]
This problem is an instance of an infamous C++ shortcoming whose name I keep forgetting. The line causing your test in PR #434 to fail is
```
MultiArray<1, double> lvMA4(Shape1(width));
```
It looks like a constructor call, but actually declares a function taking a Shape1 and returning a MultiArray (or so). The correct fix is to use initializer syntax and write
```
MultiArray<1, double> lvMA4(Shape1{width});
```
I believe that this problem was one motivation behind the introduction of the new syntax.

**Comment by fontcala** [comment]
This syntactic ambiguity's name is "Most Vexing Parse"

**Comment by emmenlau** [comment]
Thanks a lot for this interesting observation and for the solution too!
