### ISSUE TITLE
Incompatibility with numpy 1.15

### ISSUE THREAD

**Issue by stuarteberg** [ukoethe/vigra#436]
I'm noticing some strange incompatibility with numpy 1.15.  I get an error when using a boolean ("mask") indexing on a `VigraArray`:

```python
>>> import numpy as np
>>> import vigra
>>> r = np.random.randint(2, size=(3,3))
>>> r
array([[1, 1, 1],
       [1, 1, 1],
       [1, 0, 0]])

>>> # Try boolean indexing
>>> r[(r == 1)]
array([1, 1, 1, 1, 1, 1, 1])

>>> # Now repeat with a VigraArray
>>> vr = vigra.taggedView(r, 'yx')
>>> vr[(vr == 1)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniforge/envs/ilastikrag/lib/python3.6/site-packages/vigra/arraytypes.py", line 1272, in __getitem__
    res.axistags = res._transform_axistags(index)
  File "/miniforge/envs/ilastikrag/lib/python3.6/site-packages/vigra/arraytypes.py", line 485, in _transform_axistags
    return self.axistags.transform(index, self.ndim)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

There is no error using numpy 1.13 or 1.14.  I do not know if there are additional incompatibilities.  (This error triggered a test case somewhere in my code.)  I have not yet tried running the vigra test suite with numpy 1.15.

**Comment by ukoethe** [comment]
Can this warning (issued by numpy 1.15.2) explain the error?
```
vigranumpy/vigra/arraytypes.py:1263: FutureWarning: Using a non-tuple sequence 
for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. 
In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will 
result either in an error or a different result.
```

**Comment by stuarteberg** [comment]
>Can this warning (issued by numpy 1.15.2) explain the error?

I'm not sure.  But in any case, the above test code now succeeds without error when I use numpy 1.15.2.  The numpy [release notes][1] include this item:

>- The boolean indexing of subclasses now works correctly.

[1]: https://github.com/numpy/numpy/releases/tag/v1.15.2

which sounds related.  I will close this issue, since it is apparently fixed now.
