### ISSUE TITLE
Detecting libboost_python

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#445]
In some cases, `libboost_python` includes the Python major and minor version (e.g. `libboost_python36`). Would be good if we could detect this case and search for it as well.

**Comment by jakirkham** [comment]
Thanks for the update and fix.

Glad to here c-f is paying dividends. Indeed Azure looks quite promising.

Interestingly part of the reason I ask is because we were running into issues with the Windows build in c-f. Got around this issue on macOS and Linux with [a hack]( https://github.com/conda-forge/vigra-feedstock/pull/42/commits/57fb846434af46417789803861e24f1d8f1c24f4 ), but haven't been so lucky with Windows. Is there some tweak I should make to this hack for Windows or should I just try to backport a patch from the aforementioned PR?

**Comment by ukoethe** [comment]
I fixed several issues in the build process along the way (see PR #448), especially path problems in `set_path.py.in` and `run_test.bat.in`. If this is your problem, you can work around it by adding the directory containing `vigraimpex.dll` explicitly to the PATH. In any case, you can see the current build script, which doesn't require any hacks, in `azure-pipelines.yml`. I also found that VS 2017 doesn't work with the c-f dependencies, the tests crash upon `import vigra`.

**Comment by jakirkham** [comment]
Thanks Ulli. Would it make sense to do a new release with those changes? If so, do you have a timeline in mind?

**Comment by ukoethe** [comment]
@emmenlau wants to do a major code cleanup using clang-format or such. I'm planning to do a release after that, but don't yet have a concrete timeline.
