### ISSUE TITLE
Supporting Python 3.7

### ISSUE THREAD

**Issue by jakirkham** [ukoethe/vigra#450]
Would be great to start testing and support Python 3.7.

**Comment by ukoethe** [comment]
Which compiler does c-f use for Python 3.7 on the three platforms? And while we are at it: which compiler are you using for Python 2.7 on Windows?

**Comment by jakirkham** [comment]
We are in the process of migrating to the same compilers that `defaults` uses for macOS and Linux. So this means Clang 4.0.1 on macOS and GCC 7.3.0 on Linux. We still support the system compiler we have been using as a legacy toolchain. Though this will likely be dropped once the migration is complete.

On Windows, we are using Visual Studio 2015 for Python 3.5+ (though Python 3.5 itself is being dropped currently).

With Python 2.7 conda-forge supports two options, Visual Studio 2008 or MSYS2's GCC 5.3.0. Currently not building VIGRA for Python 2.7 as the C++ requirements are not met by Visual Studio 2008 and AFAICT the dependency requirements are not met using the MSYS2 stack.

**Comment by ukoethe** [comment]
@emmenlau Do you know (or can you find out) how we can use Clang 4.0.1 in an azure MacOS-VM, as will be needed for Python 3.7 according to the above comment?

**Comment by jakirkham** [comment]
Should add packages that have been rebuilt are published to [a separate label called `gcc7`]( https://anaconda.org/conda-forge/repo/files?type=any&label=gcc7 ) (this includes both the Clang 4.0.1 packages on macOS and GCC 7.3.0 packages on Linux). These will eventually graduate to the `main` label once the rebuild completes. Status on the rebuild can be seen on [this page]( https://conda-forge.org/status/ ). We still have some ways to go, but some of the hard packages are done already.

All of VIGRA's dependencies should be satisfied; hence, we are working on rebuilding VIGRA with the new compilers in PR ( https://github.com/conda-forge/vigra-feedstock/pull/43 ). Looks like one of the bugs you already fixed. ( https://github.com/ukoethe/vigra/pull/415 ) 😄

Also recently went through this change with a package of ours. If you use a `conda-build` recipe, it is as simple as adding [this line]( https://github.com/nanshe-org/rank_filter/blob/2a923a6929640dbe42a707b68930f31012219f0f/rank_filter.recipe/meta.yaml#L10 ).

**Comment by ukoethe** [comment]
> published to a separate label called gcc7

We already use this label in our Linux builds on azure, because the `main` label did not work, IIRC. Didn't know that the `gcc7` label also applies to macOS.

> as simple as adding this line
```
 - {{ compiler("cxx") }}
```

What compiler will option `cxx` select, and which options are available?

**Comment by jakirkham** [comment]
Ah ok. Then you're ahead of the curve. 😄

By default, `conda-build` will look at [this list]( https://github.com/conda/conda-build/blob/3.16.1/conda_build/variants.py#L41-L76 ). It this postfixes this with `_{os}-{arch}` (e.g. `gxx` on Linux becomes `gxx_linux-64`). One can override this list with variants in `conda_build_config.yaml`, which we do for [the legacy compilers in `conda-forge`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L11-L32 ). One can also do this with a `conda_build_config.yaml` in the recipe directory itself or via a CLI option if there are different variants one would like to try. There's more details about the [`defaults` compilers in this section]( https://conda.io/docs/user-guide/tasks/build-packages/variants.html#compiler-packages ) (though other relevant information is on that page generally).

**Comment by jakirkham** [comment]
Looks like that patch was all we needed for Python 3.7 support.

Unfortunately we now have [a segfault on macOS]( https://github.com/conda-forge/vigra-feedstock/pull/43#issuecomment-431461760 ) though.
