### ISSUE TITLE
How to deal with random failures in testing?

### ISSUE THREAD

**Issue by emmenlau** [ukoethe/vigra#455]
It seems that with low probability I get failed tests in Azure. Out of 2-3 builds, roughly one fails on one of the platforms. In the past ~30 builds, I had 5-6 failed tests on Linux and 5-6 failed tests on MacOSX. Typically its the classifier test that fails, but other tests have failed as well, After a rebuild, the problems are gone. No tests have failed for me locally.

**Comment by ukoethe** [comment]
I noticed these failures as well (they have been in the code for a long time), but have no idea how to track the problem down, given how difficult it is to reproduce the problem locally or to debug a CI build directly. If you find a local setup that reliably reproduces the issue, I might be able to look into it. For the time being, simply restart the failing build.

**Comment by emmenlau** [comment]
I guess this can be closed now.
