### ISSUE TITLE
Buid error with sphinx >= 1.8.0

### ISSUE THREAD

**Issue by ametzler** [ukoethe/vigra#462]
Hello,

according to http://www.sphinx-doc.org/en/master/changes.html was dropped in 1.8.0 and indeed with sphinx 1.8.4 `make doc_python` fails with
```
Running Sphinx v1.8.4
Working directory: /dev/shm/VIGRA/vigra/build/vigranumpy
vigraimpex path: /dev/shm/VIGRA/vigra/build/src/impex

Extension error:
Could not import extension sphinx.ext.pngmath (exception: No module named 'sphinx.ext.pngmath')
make[3]: *** [vigranumpy/docsrc/CMakeFiles/doc_python.dir/build.make:62: vigranumpy/docsrc/CMakeFiles/doc_python] Error 2
```

**Comment by tillea** [comment]
Here you can find a [patch](https://salsa.debian.org/science-team/libvigraimpex/blob/debian/buster/debian/patches/sphinx.ext.pngmath.patch) which I used in the Debian package.

**Comment by hmeine** [comment]
Thanks! (You could make it easier to review & merge changes through pull requests, though.)
