### ISSUE TITLE
how can I use vigra in c++ project

### ISSUE THREAD

**Issue by cydcydcyd** [ukoethe/vigra#465]
I try to compile the library and get some errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4025	The project file could not be loaded. 'TARGET_FILE_DIR' is an undeclared prefix. Line 7, position 38.	check_cpp	D:\lib\master\vigra-master\test\fourier\test_fourier.vcxproj.user	7

**Comment by hmaarrfk** [comment]
Sorry for the lack of response in a long time.

Please reopen a new issue providing the environment specifics, and the command used to reach the point above.
