### ISSUE TITLE
Compilation Problem with Mingw64 and recent git snapshot

### ISSUE THREAD

**Issue by mmatthe** [ukoethe/vigra#466]
Within the file `include/rgbvalue.hxx`, some template class names are `DIFFERENCE`. This collides with a strange define within the file [`winuser.h` within the mingw-w64 package](https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/winuser.h#l135).

**Comment by hmaarrfk** [comment]
Please try again with a more recent snapshot. 

Let us know if you face any new issues.
