### ISSUE TITLE
c++17 support?

### ISSUE THREAD

**Issue by k-dominik** [ukoethe/vigra#481]
The clang folks have implemented c++17 a bit more aggressively than gcc: some members that were deprecated in c++17 are removed, like `std::bind1st`, `std::bind2nd` as used in e.g. [` vigra/include/vigra/numpy_array_traits.hxx `](https://github.com/ukoethe/vigra/blob/fb427440da8c42f96e14ebb60f7f22bdf0b7b1b2/include/vigra/numpy_array_traits.hxx#L765).

gcc [seems to be keeping those](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91383) for the time being.

For projects that link against vigra this poses a problem: on osx those projects cannot be compiled using `c++17`. Are there any plans to add support for this? Or, are there plans to support standards older than `c++11`? Otherwise one can use lambdas instead...

**Comment by BSeppke** [comment]
Would be interesting for me as well. MS also dropped these functions in their C++ compiler when switching to the C++17 langange standard.

**Comment by constantinpape** [comment]
I ran into this again recently. Would be great to enable c++17 builds with vigra as dependency.
@ukoethe @hmeine I would not mind making these changes; is there any interest from your side in having this?
Also, if I do this I would need a new vigra release to get this merged into conda forge to use the changes in other conda builds.
