### ISSUE TITLE
Vigra pollutes builds with pragmas that suppress warnings

### ISSUE THREAD

**Issue by samkhal** [ukoethe/vigra#482]
`config.hxx` currently uses compiler-specific warning suppression pragmas, such as [here](https://github.com/ukoethe/vigra/blob/aaaf44d240aebd0eb3539b6e105a19a984000d81/include/vigra/config.hxx#L166). This pollutes the build of anyone including this file who relies on the suppressed warnings, particularly for anyone also using `-Werror`, as this introduces compile errors that are dependent on where vigra is first included.

If suppressing these warnings from within vigra is desired, `push` and `pop` pragmas should be used to apply and reset these suppressions when entering and leaving vigra code.

**Comment by hmaarrfk** [comment]
We finally got our CIs running again. if you want to make a PR to address this, I would be happy to review it.
