### ISSUE TITLE
PyPy Support

### ISSUE THREAD

**Issue by hmaarrfk** [ukoethe/vigra#484]
We are working toward getting pypy support at conda-forge.

Vigra seems to have trouble finding the appropriate python libraries.

I think it is related to the use of the old `FIND_PACKAGE` calls in cmake.

https://cmake.org/cmake/help/git-stage/module/FindPython.html

cmake 3.12 seems to have new function calls that improve on pypy detection (that may have been 3.18 but i'm not too sure).

Would it be appropriate to make PRs toward bumping the minimum CMAKE version to make this a reality?

**Comment by hmeine** [comment]
It sounds good and appropriate; if nobody else reviews your PR, I would.

**Comment by hmaarrfk** [comment]
new cmake in use now.
