### ISSUE TITLE
Matlab in MacOC: I got vigra compile again!

### ISSUE THREAD

**Issue by tschuldigung** [ukoethe/vigra#512]
Hi zusammen

@hmeine @hmaarrfk 
mit nur 5 Zeilen Änderung konnte ich VIGRA in Matlab unter MacOS wieder bauen und erfolgreich RandomForest trainieren. Leider kann ich den BRanch nicht einchecken, um einen PR zu erstellen - habe es mit https und PAT versucht, aber es kommt nur Error 403. Sind die Rechte eingeschränkt auf explizit vergebene Accounts?

Ich habe vigra das letzte Mal aktiv vor10 Jahren benutzt, als Doktorand beim HCI, daher kenne ich die Library und Uli. Schön, wie sie sich weiterentwickelt hat!

VG
Joachim Börger

**Comment by hmaarrfk** [comment]
> with only 5 lines change I was able to rebuild VIGRA in Matlab under MacOS and successfully train RandomForest. Unfortunately, I can't check in the BRanch to create a PR - I've tried https and PAT, but I only get Error 403. Are the rights restricted to explicitly assigned accounts?
>
> I last actively used vigra 10 years ago as a PhD student at HCI, so I know the library and Uli. It's great how it has evolved!

You should probably fork the repository, and create a branch there.

There is the general problem of: https://github.com/ukoethe/vigra/issues/506

**Comment by tschuldigung** [comment]
Fork and thus leave all other Matlab MacOs users without the fix - and unable to use vigra? That would be a pity.

The error appearing says:
Pushing to https://github.com/ukoethe/vigra.git
remote: Permission to ukoethe/vigra.git denied to tschuldigung.
fatal: unable to access 'https://github.com/ukoethe/vigra.git/': The requested URL returned error: 403
Completed with errors, see above

How to solve that?  Can you add my user account s.t. I cn push sth?

**Comment by hmaarrfk** [comment]
sorry, i meant, fork, and make a branch, then make a pull request. This is typically the model that github development follows.

**Comment by hmaarrfk** [comment]
See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models#fork-and-pull-model

**Comment by tschuldigung** [comment]
Thanks for the hint! I created a fork and a PR, see above link

**Comment by hmaarrfk** [comment]
merged recently. thanks.
