### ISSUE TITLE
Use of deprecated std::unary_negate and std::binary_negate

### ISSUE THREAD

**Issue by mkrausex** [ukoethe/vigra#534]
The file `functortraits.hxx` refers to `std::unary_negate` and `std::binary_negate`, which have been deprecated since C++17, and removed in C++20. Therefore, this file fails to compile under Visual Studio 2019 in C++20 mode, which is the environment the project I'm working on uses.

I commented these out (see [attached patch](https://github.com/ukoethe/vigra/files/10791651/negate.patch)), and my project is fine with that change. However, I’m not sure what implications that has on other code, and what a real fix could be.

**Comment by lnw** [comment]
The change looks completely reasonable to me.

Although, the fact that it works for your project only means that your project doesn't pass std::unary_negate<T> to any high level vigra-function that would apply FunctorTraits to it.  So, you are effectively removing functionality from the library.  If we think that is used, one could write a replacement, but there isn't a simple drop in replacement.

**Comment by hmaarrfk** [comment]
Closed by https://github.com/ukoethe/vigra/pull/536 

thank you
