### ISSUE TITLE
1.11.2 release is configured as 1.11.1

### ISSUE THREAD

**Issue by moubctez** [ukoethe/vigra#551]
In 1.11.2 release, `include/vigra/config_version.hxx` still contains version 1.11.1.

```
#ifndef VIGRA_CONFIG_VERSION_HXX
#define VIGRA_CONFIG_VERSION_HXX

    #define VIGRA_VERSION_MAJOR 1
    #define VIGRA_VERSION_MINOR 11
    #define VIGRA_VERSION_PATCH 1
    #define VIGRA_VERSION "1.11.1"

#endif /* VIGRA_CONFIG_VERSION_HXX */
```

**Comment by hmaarrfk** [comment]
I don't have a solution for the past releases, but I added this in our "How to make a release note" and set the master version to 1.11.2
