### ISSUE TITLE
Gaussian Smoothing and time axistag conflict

### ISSUE THREAD

**Issue by lfiaschi** [ukoethe/vigra#63]
Hi, I cannot smooth a 4d vigra array with t as last axistag:

The following code:
import vigra
import numpy

shape=(20,20,20,20)
a=vigra.VigraArray(shape)
print a.axistags

vigra.filters.gaussianSmoothing(a,1)

axistags=vigra.defaultAxistags(5)
axistags.dropChannelAxis()
import copy

a.axistags=copy.copy(axistags)
print "Here"
print a.axistags
vigra.filters.gaussianSmoothing(a,1)

has the following output:

AxisInfo: 'x' (type: Space)
AxisInfo: 'y' (type: Space)
AxisInfo: 'z' (type: Space)
AxisInfo: 'c' (type: Channels)

Here
AxisInfo: 'x' (type: Space)
AxisInfo: 'y' (type: Space)
AxisInfo: 'z' (type: Space)
AxisInfo: 't' (type: Time)

Traceback (most recent call last):
  File "/home/lfiaschi/SPYDER/TEST/untitled0.py", line 26, in <module>
    vigra.filters.gaussianSmoothing(a,1)
Boost.Python.ArgumentError: Python argument types in
    vigra.filters.gaussianSmoothing(VigraArray, int)
did not match C++ signature:
    gaussianSmoothing(vigra::NumpyArray<4u, vigra::Multiband<float>, vigra::StridedArrayTag> volume, boost::python::tuple sigmas, vigra::NumpyArray<4u, vigra::Multiband<float>, vigra::StridedArrayTag> out=None)
    gaussianSmoothing(vigra::NumpyArray<4u, vigra::Multiband<float>, vigra::StridedArrayTag> volume, double sigma, vigra::NumpyArray<4u, vigra::Multiband<float>, vigra::StridedArrayTag> out=None)
    gaussianSmoothing(vigra::NumpyArray<3u, vigra::Multiband<float>, vigra::StridedArrayTag> image, boost::python::tuple sigmas, vigra::NumpyArray<3u, vigra::Multiband<float>, vigra::StridedArrayTag> out=None)
    gaussianSmoothing(vigra::NumpyArray<3u, vigra::Multiband<float>, vigra::StridedArrayTag> image, double sigma, vigra::NumpyArray<3u, vigra::Multiband<float>, vigra::StridedArrayTag> out=None)

**Comment by ukoethe** [comment]
fixed in 4afe9531997801b97f53bbcfcc464f5aefedc300
