### ISSUE TITLE
cmake PythonInterp and PythonLibs do not match on MacOS

### ISSUE THREAD

**Issue by miheld** [ukoethe/vigra#84]
maybe a general cmake issue, but cmake FIND_PACKAGE(PythonInterp) and FIND_PACKAGE(PythonLibs) do not find the same Python version.

Python 2.7.2 was build from source as a Framework and the PATH is set correctly. Calling "python" in the shell opens Python 2.7.2 as expected

cmake output (cmake 2.8.5 on MacOS 10.6.8):
...
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/Current/bin/python2.7 
-- Checking VIGRANUMPY_DEPENDENCIES
-- Searching for Boost (at least version 1.40.0)
-- Searching for Boost (at least version 1.40.0) in /usr/local/cecog_dependencies
-- Boost version: 1.44.0
-- Found the following Boost libraries:
--   python
-- Found PythonLibs: /usr/lib/libpython2.6.dylib 
-- Searching for Python numpy: ok
-- Searching for Python nosetests: ok
-- Searching for sphinx documentation generator: ok
-- Found VIGRANUMPY_DEPENDENCIES: TRUE 
...

it should be
-- Found PythonLibs: /usr/local/lib/libpython2.7.dylib 

the problem could be solved by

sudo ln -s /Library/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib /usr/local/lib/libpython2.7.dylib

although it's not clear why cmake locates Python correctly but not its lib

(this text should maybe go to a installation FAQ and might be helpful for people struggling with MacOS)

**Comment by ukoethe** [comment]
Fixed by c0fd13d7fd0d0884369ca888300e6d24a360a8bc and subsequent improvements.
