### ISSUE TITLE
C++ modules/libraries not found for vigranumpy on MacOS 

### ISSUE THREAD

**Issue by miheld** [ukoethe/vigra#85]
when installing vigranumpy on MacOS dependent libraries are not found. 

python -c "import vigra"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vigra/__init__.py", line 103, in <module>
    import impex
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vigra/impex.so, 2): Library not loaded: libvigraimpex.4.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vigra/impex.so
  Reason: image not found

looking into impex.so:

otool -L impex.so 
impex.so:
        impex.so (compatibility version 0.0.0, current version 0.0.0)
        libvigraimpex.4.dylib (compatibility version 4.0.0, current version 4.180.0)
        /usr/local/cecog_dependencies/lib/libhdf5.7.dylib (compatibility version 8.0.0, current version 8.1.0)
        /usr/local/cecog_dependencies/lib/libhdf5_hl.7.dylib (compatibility version 8.0.0, current version 8.1.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.3)
        /usr/local/cecog_dependencies//lib/libsz.2.dylib (compatibility version 3.0.0, current version 3.0.0)
        /Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
        /usr/local/cecog_dependencies//lib/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/local/cecog_dependencies/lib/libjpeg.8.dylib (compatibility version 12.0.0, current version 12.0.0)
        /usr/local/cecog_dependencies/lib/libpng15.15.dylib (compatibility version 21.0.0, current version 21.0.0)
        /usr/local/cecog_dependencies/lib/libtiff.3.dylib (compatibility version 13.0.0, current version 13.5.0)
        /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)

impex.so and  libvigraimpex.4.dylib  are given w/o absolute path. setting DYLD_LIBRARY_PATH on MacOS would do the trick but that is a debug-only mode and not recommended

the solution would be to specify the library IDs with absolute name before linking. I assume the cmake install has to be changed for MacOS.

I wrote a shell script that changes all VIGRA library dependencies for all vigranumpy .so files. this works very well also in combination with py2app (where the dependencies are set relative to the executable)

fix_install_names.sh:
export INSTALL_PREFIX=/usr/local/cecog_dependencies/lib
export INSTALL_PREFIX2=/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vigra

sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/analysis.so
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/colors.so
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/filters.so
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/fourier.so 
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/geometry.so 
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/impex.so
sudo install_name_tool -change libvigraimpex.4.dylib $INSTALL_PREFIX/libvigraimpex.4.dylib $INSTALL_PREFIX2/impex.so
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/learning.so
sudo install_name_tool -change libvigraimpex.4.dylib $INSTALL_PREFIX/libvigraimpex.4.dylib $INSTALL_PREFIX2/learning.so
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/noise.so
sudo install_name_tool -change vigranumpycore.so $INSTALL_PREFIX2/vigranumpycore.so $INSTALL_PREFIX2/sampling.so

**Comment by ukoethe** [comment]
Fixed a long time ago...
